### ISSUE TITLE
Question about the ground station setup. Does it still use the EZ-WifiBroadcast as backend? 

### ISSUE THREAD

**Issue by villimikko** [RomanLut/hx-esp32-cam-fpv#4]
Is there possibility to use the wfb-ng as groundsatiton base? 

I thik it just got support for android devices with powerful encoding abilities!

**Comment by RomanLut** [comment]
wfb-ng-based projects like openipc expect h264 or h265 stream, esp32 can send mjpeg only. 
You still can use the same ground station hardware but with esp32-cam-fpv groundstation software.
