### ISSUE TITLE
Using ubuntu laptop as Groundstation?

### ISSUE THREAD

**Issue by villimikko** [RomanLut/hx-esp32-cam-fpv#6]
How easy would it be to use ubuntu laptop as basestation or Jetson nano as groundstation instead of raspberry pi?. 

Would these be recomended at all?

**Comment by RomanLut** [comment]
It should be possible to run GS software on both systems, but I did not tried it. 
GS has been working on Unbuntu for me at early development stages.

You can try following https://github.com/RomanLut/hx-esp32-cam-fpv/blob/master/doc/building_gs_image.md steps on ubuntu or jetson.

RPI2W is recommented.

**Comment by ugnich** [comment]
Here is the manual for Fedora Linux, it should not be much different on Ubuntu: https://github.com/RomanLut/hx-esp32-cam-fpv/blob/master/doc/building_gs_fedora.md
