### ISSUE TITLE
Which glasses is used

### ISSUE THREAD

**Issue by Ncerzzk** [RomanLut/hx-esp32-cam-fpv#8]
Hi, It seems the glasses you use to test in README.md has a HDMI input?
Actually I'm struggling finding a suitable display for this project for a long time and I'm know little about glasses

(other words, great work you did in this project! )

Thank you

**Comment by RomanLut** [comment]
Skyzone SKY030. Has HDMI input, can do 1920x1080, but project is using 1280x720x60.
I plan to implement AV glasses support; 800x456 is  close to 720x576 pal.
Currently having problem to initialize SDL wih AV output.

**Comment by Ncerzzk** [comment]
Thank you, got it. support AV glasses seems quite promising！
